---
sidebar: sidebar 
permalink: trident-docker/collect-logs-docker.html 
keywords: deploy, Trident, trident for docker, docker, logs, binary, managed plugin 
summary: 'Vous pouvez collecter les journaux pour obtenir de l"aide lors du dépannage. La méthode que vous utilisez pour collecter les journaux varie selon la façon dont vous exécutez le plugin Docker.' 
---
= Collecter les journaux
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez collecter les journaux pour obtenir de l'aide lors du dépannage. La méthode que vous utilisez pour collecter les journaux varie selon la façon dont vous exécutez le plugin Docker.



== Collecter les journaux pour le dépannage

.Étapes
. Si vous exécutez Trident en utilisant la méthode de plugin géré recommandée (c'est-à-dire en utilisant  `docker plugin` commandes), consultez-les comme suit :
+
[source, console]
----
docker plugin ls
----
+
[listing]
----
ID                  NAME                DESCRIPTION                          ENABLED
4fb97d2b956b        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
journalctl -u docker | grep 4fb97d2b956b
----
+
Le niveau de journalisation standard devrait vous permettre de diagnostiquer la plupart des problèmes. Si cela ne suffit pas, vous pouvez activer la journalisation de débogage.

. Pour activer la journalisation de débogage, installez le plugin avec la journalisation de débogage activée :
+
[source, console]
----
docker plugin install netapp/trident-plugin:<version> --alias <alias> debug=true
----
+
Ou, activez la journalisation de débogage lorsque le plugin est déjà installé :

+
[source, console]
----
docker plugin disable <plugin>
----
+
[source, console]
----
docker plugin set <plugin> debug=true
----
+
[source, console]
----
docker plugin enable <plugin>
----
. Si vous exécutez le fichier binaire directement sur l’hôte, les journaux sont disponibles dans le répertoire  `/var/log/netappdvp` de l’hôte. Pour activer la journalisation de débogage, spécifiez  `-debug` lors de l’exécution du plugin.




== Conseils généraux de dépannage

* Le problème le plus fréquent rencontré par les nouveaux utilisateurs est une erreur de configuration empêchant l'initialisation du plugin. Lorsque cela se produit, vous verrez probablement un message comme celui-ci lorsque vous essayerez d'installer ou d'activer le plugin :
+
`Error response from daemon: dial unix /run/docker/plugins/<id>/netapp.sock: connect: no such file or directory`

+
Cela signifie que le plugin n'a pas pu démarrer. Heureusement, le plugin a été conçu avec une capacité de journalisation complète qui devrait vous aider à diagnostiquer la plupart des problèmes que vous êtes susceptible de rencontrer.

* En cas de problème lors du montage d'un PV dans un conteneur, assurez-vous que  `rpcbind` est installé et en cours d'exécution. Utilisez le gestionnaire de paquets requis pour le système d'exploitation hôte et vérifiez si  `rpcbind` est en cours d'exécution. Vous pouvez vérifier l'état du service rpcbind en exécutant une  `systemctl status rpcbind` ou une commande équivalente.

