---
sidebar: sidebar 
permalink: trident-docker/multiple-instances-docker.html 
keywords: deploy, Trident, docker, trident for docker, managed plugin, trident instances, alias 
summary: 'Plusieurs instances de Trident sont nécessaires lorsque vous souhaitez disposer simultanément de plusieurs configurations de stockage. La clé pour utiliser plusieurs instances est de leur donner des noms différents à l"aide de l"option --alias avec le plugin conteneurisé, ou de l"option --volume-driver lors de l"instanciation de Trident sur l"hôte.' 
---
= Gérer plusieurs instances Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Plusieurs instances de Trident sont nécessaires lorsque vous souhaitez disposer simultanément de plusieurs configurations de stockage. La clé pour utiliser plusieurs instances est de leur donner des noms différents en utilisant l’ `--alias`option avec le plugin conteneurisé, ou l’ `--volume-driver`option lors de l’instanciation de Trident sur l’hôte.



== Étapes pour le plugin géré par Docker (version 1.13/17.03 ou ultérieure)

. Lancez la première instance en spécifiant un alias et un fichier de configuration.
+
[source, console]
----
docker plugin install --grant-all-permissions --alias silver netapp/trident-plugin:21.07 config=silver.json
----
. Lancez la deuxième instance en spécifiant un alias différent et un fichier de configuration.
+
[source, console]
----
docker plugin install --grant-all-permissions --alias gold netapp/trident-plugin:21.07 config=gold.json
----
. Créez des volumes en spécifiant l'alias comme nom du pilote.
+
Par exemple, pour le volume gold :

+
[source, console]
----
docker volume create -d gold --name ntapGold
----
+
Par exemple, pour le volume silver :

+
[source, console]
----
docker volume create -d silver --name ntapSilver
----




== Étapes pour la version traditionnelle (1.12 ou antérieure)

. Lancez le plugin avec une configuration NFS en utilisant un ID de pilote personnalisé :
+
[source, console]
----
sudo trident --volume-driver=netapp-nas --config=/path/to/config-nfs.json
----
. Lancez le plugin avec une configuration iSCSI en utilisant un ID de pilote personnalisé :
+
[source, console]
----
sudo trident --volume-driver=netapp-san --config=/path/to/config-iscsi.json
----
. Provisionnez des volumes Docker pour chaque instance de pilote :
+
Par exemple, pour NFS :

+
[source, console]
----
docker volume create -d netapp-nas --name my_nfs_vol
----
+
Par exemple, pour iSCSI :

+
[source, console]
----
docker volume create -d netapp-san --name my_iscsi_vol
----

