---
sidebar: sidebar 
permalink: faq.html 
keywords: faq, frequently asked questions 
summary: 'Trouvez les réponses aux questions fréquemment posées concernant l"installation, la configuration, la mise à niveau et le dépannage Trident.' 
---
= Foire aux questions
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Trouvez les réponses aux questions fréquemment posées concernant l'installation, la configuration, la mise à niveau et le dépannage Trident.



== Questions générales



=== À quelle fréquence Trident est-il publié ?

À compter de la version 24.02, Trident est publié tous les quatre mois : février, juin et octobre.



=== Trident prend-il en charge toutes les fonctionnalités publiées dans une version particulière de Kubernetes ?

Trident ne prend généralement pas en charge les fonctionnalités alpha de Kubernetes. Trident peut prendre en charge les fonctionnalités bêta dans les deux versions de Trident qui suivent la version bêta de Kubernetes.



=== Trident a-t-il des dépendances à d'autres produits NetApp pour son fonctionnement ?

Trident ne dépend d'aucun autre produit logiciel NetApp et fonctionne comme une application autonome. Cependant, vous devez disposer d'un périphérique de stockage NetApp.



=== Comment puis-je obtenir tous les détails de configuration de Trident ?

Utilisez la commande  `tridentctl get` pour obtenir plus d'informations sur votre configuration Trident.



=== Puis-je obtenir des métriques sur la manière dont le stockage est provisionné par Trident ?

Oui. Les points de terminaison Prometheus peuvent être utilisés pour recueillir des informations sur le fonctionnement de Trident, telles que le nombre de backends gérés, le nombre de volumes provisionnés, les octets consommés, etc. Vous pouvez également utiliser link:https://docs.netapp.com/us-en/cloudinsights/["Cloud Insights"^] pour la surveillance et l'analyse.



=== L'expérience utilisateur change-t-elle lors de l'utilisation de Trident en tant que CSI Provisioner ?

Non. L'expérience utilisateur et les fonctionnalités restent inchangées. Le nom du provisionneur utilisé est  `csi.trident.netapp.io`. Cette méthode d'installation de Trident est recommandée si vous souhaitez utiliser toutes les nouvelles fonctionnalités des versions actuelles et futures.



== Installer et utiliser Trident sur un cluster Kubernetes



=== Trident prend-il en charge une installation hors ligne à partir d'un registre privé ?

Oui, Trident peut être installé hors ligne. Voir link:../trident-get-started/kubernetes-deploy.html["Découvrez l'installation de Trident"^].



=== Puis-je installer Trident à distance ?

Oui. Trident 18.10 et versions ultérieures prennent en charge la capacité d'installation à distance depuis n'importe quelle machine qui a `kubectl` accès au cluster. Après que `kubectl` l'accès a été vérifié (par exemple, initiez une `kubectl get nodes` commande depuis la machine distante pour vérifier), suivez les instructions d'installation.



=== Puis-je configurer la haute disponibilité avec Trident ?

Trident est installé en tant que déploiement Kubernetes (ReplicaSet) avec une seule instance, ce qui lui confère une haute disponibilité intégrée. Vous ne devez pas augmenter le nombre de réplicas dans le déploiement. Si le nœud où Trident est installé est perdu ou si le pod est autrement inaccessible, Kubernetes redéploie automatiquement le pod sur un nœud sain de votre cluster. Trident est uniquement un composant du plan de contrôle, donc les pods actuellement montés ne sont pas affectés si Trident est redéployé.



=== Trident a-t-il besoin d'accéder à l'espace de noms kube-system ?

Trident lit à partir du serveur d'API Kubernetes pour déterminer quand les applications demandent de nouveaux PVC, il a donc besoin d'accéder à kube-system.



=== Quels sont les rôles et privilèges utilisés par Trident ?

L'installateur Trident crée un ClusterRole Kubernetes, qui dispose d'un accès spécifique aux ressources PersistentVolume, PersistentVolumeClaim, StorageClass et Secret du cluster Kubernetes. Reportez-vous à link:trident-get-started/kubernetes-customize-deploy-tridentctl.html["Personnaliser l'installation de tridentctl"^].



=== Puis-je générer localement les fichiers manifestes exacts que Trident utilise pour l'installation ?

Vous pouvez générer et modifier localement les fichiers manifestes exacts utilisés par Trident pour l'installation, si nécessaire. Consultez link:trident-get-started/kubernetes-customize-deploy-tridentctl.html["Personnaliser l'installation de tridentctl"^].



=== Puis-je partager le même backend SVM ONTAP pour deux instances Trident distinctes pour deux clusters Kubernetes distincts ?

Bien que cela soit déconseillé, vous pouvez utiliser le même SVM backend pour deux instances Trident. Spécifiez un nom de volume unique pour chaque instance lors de l'installation et/ou indiquez un paramètre unique  `StoragePrefix` dans le fichier  `setup/backend.json`. Cela permet de garantir que le même volume FlexVol n'est pas utilisé pour les deux instances.



=== Est-il possible d'installer Trident sous ContainerLinux (anciennement CoreOS) ?

Trident est simplement un pod Kubernetes et peut être installé partout où Kubernetes est en cours d'exécution.



=== Puis-je utiliser Trident avec NetApp Cloud Volumes ONTAP ?

Oui, Trident est pris en charge sur AWS, Google Cloud et Azure.



== Dépannage et support



=== Est-ce que NetApp prend en charge Trident ?

Bien que Trident soit open source et fourni gratuitement, NetApp le prend entièrement en charge à condition que votre backend NetApp soit pris en charge.



=== Comment puis-je ouvrir un dossier d'assistance

Pour ouvrir un dossier de demande d'assistance, effectuez l'une des opérations suivantes :

. Contactez votre Support Account Manager et obtenez de l'aide pour créer un ticket.
. Ouvrez un ticket d'assistance en contactant https://www.netapp.com/company/contact-us/support/["Support NetApp"^].




=== Comment générer un bundle de journal de support ?

Vous pouvez créer un bundle de support en exécutant  `tridentctl logs -a`. En plus des journaux inclus dans le bundle, capturez le journal kubelet pour diagnostiquer les problèmes de montage côté Kubernetes. Les instructions pour obtenir le journal kubelet varient selon la façon dont Kubernetes est installé.



=== Que dois-je faire si je dois soumettre une demande pour une nouvelle fonctionnalité ?

Créez un ticket sur  https://github.com/NetApp/trident["Trident Github"^] et mentionnez *RFE* dans l'objet et la description du problème.



=== Où dois-je signaler un défaut ?

Créez un ticket sur  https://github.com/NetApp/trident["Trident Github"^]. Veillez à inclure toutes les informations et les journaux nécessaires relatifs à ce problème.



=== Que se passe-t-il si j'ai une question rapide sur Trident et que j'ai besoin d'éclaircissements ? Existe-t-il une communauté ou un forum ?

Si vous avez des questions, des problèmes ou des demandes, contactez-nous via notre Trident link:https://discord.gg/NetApp["Chaîne Discord"^] ou GitHub.



=== Le mot de passe de mon système de stockage a changé et Trident ne fonctionne plus, comment puis-je le récupérer ?

Mettez à jour le mot de passe du backend avec  `tridentctl update backend myBackend -f </path/to_new_backend.json> -n trident`. Remplacez  `myBackend` dans l'exemple par le nom de votre backend, et  ``/path/to_new_backend.json` par le chemin d'accès au fichier  `backend.json` correct.



=== Trident ne parvient pas à trouver mon nœud Kubernetes. Comment puis-je résoudre ce problème ?

Il existe deux scénarios probables pour lesquels Trident ne peut pas trouver un nœud Kubernetes. Cela peut être dû à un problème de réseau au sein de Kubernetes ou à un problème de DNS. Le daemonset de nœud Trident qui s'exécute sur chaque nœud Kubernetes doit pouvoir communiquer avec le contrôleur Trident pour enregistrer le nœud auprès de Trident. Si des modifications réseau sont survenues après l'installation de Trident, vous ne rencontrez ce problème qu'avec les nouveaux nœuds Kubernetes ajoutés au cluster.



=== Si le pod Trident est détruit, vais-je perdre les données ?

Les données ne seront pas perdues si le pod Trident est détruit. Les métadonnées Trident sont stockées dans des objets CRD. Tous les PV qui ont été provisionnés par Trident fonctionneront normalement.



== Mettre à niveau Trident



=== Puis-je passer directement d'une version antérieure à une version plus récente (en sautant quelques versions) ?

NetApp prend en charge la mise à niveau de Trident d'une version majeure à la version majeure suivante. Vous pouvez effectuer une mise à niveau de la version 18.xx à 19.xx, de 19.xx à 20.xx, et ainsi de suite. Vous devez tester la mise à niveau dans un environnement de test avant le déploiement en production.



=== Est-il possible de rétrograder Trident vers une version précédente ?

Si vous avez besoin d’un correctif pour des bugs observés après une mise à niveau, des problèmes de dépendances ou une mise à niveau infructueuse ou incomplète, vous devez link:trident-managing-k8s/uninstall-trident.html["désinstaller Trident"] et réinstaller la version précédente en utilisant les instructions spécifiques à cette version. C’est la seule méthode recommandée pour revenir à une version antérieure.



== Gérer les backends et les volumes



=== Dois-je définir à la fois les LIF de gestion et de données dans un fichier de définition backend ONTAP ?

Le LIF de gestion est obligatoire. Le DataLIF varie :

* ONTAP SAN : Ne spécifiez pas pour iSCSI. Trident utilise link:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["Mappage LUN sélectif ONTAP"^] pour découvrir les LIF iSCSI nécessaires à l’établissement d’une session multi-chemin. Un avertissement est généré si  `dataLIF` est explicitement défini. Consultez link:trident-use/ontap-san-examples.html["Options et exemples de configuration SAN ONTAP"] pour plus de détails.
* ONTAP NAS : NetApp recommande de spécifier  `dataLIF`. Si ce n'est pas fourni, Trident récupère les dataLIF depuis la SVM. Vous pouvez spécifier un nom de domaine complet (FQDN) à utiliser pour les opérations de montage NFS, ce qui vous permet de créer un DNS à répartition de charge (round-robin) entre plusieurs dataLIF. Consultez link:trident-use/ontap-nas-examples.html["Options et exemples de configuration ONTAP NAS"] pour plus de détails




=== Trident peut-il configurer CHAP pour les backends ONTAP ?

Oui. Trident prend en charge le protocole CHAP bidirectionnel pour les backends ONTAP. Cela nécessite de définir  `useCHAP=true` dans la configuration de votre backend.



=== Comment gérer les règles d'export avec Trident ?

Trident peut créer et gérer dynamiquement des règles d'export à partir de la version 20.04. Cela permet à l'administrateur de stockage de fournir un ou plusieurs blocs CIDR dans sa configuration backend et à Trident d'ajouter les adresses IP des nœuds qui se trouvent dans ces plages à une règle d'export qu'il crée. De cette manière, Trident gère automatiquement l'ajout et la suppression des règles pour les nœuds dont les adresses IP se trouvent dans les CIDR donnés.



=== Les adresses IPv6 peuvent-elles être utilisées pour les Management et DataLIFs ?

Trident prend en charge la définition d'adresses IPv6 pour :

* `managementLIF` et  `dataLIF` pour les backends NAS ONTAP.
* `managementLIF` pour les backends SAN ONTAP. Vous ne pouvez pas spécifier  `dataLIF` sur un backend SAN ONTAP.


Trident doit être installé en utilisant le flag  `--use-ipv6` (pour  `tridentctl` l'installation),  `IPv6` (pour Trident operator), ou  `tridentTPv6` (pour l'installation Helm) pour qu'il fonctionne sur IPv6.



=== Est-il possible de mettre à jour le LIF de gestion sur le backend ?

Oui, il est possible de mettre à jour le LIF de gestion backend à l'aide de la commande  `tridentctl update backend`.



=== Est-il possible de mettre à jour le DataLIF sur le backend ?

Vous pouvez mettre à jour le DataLIF sur  `ontap-nas` et  `ontap-nas-economy` uniquement.



=== Puis-je créer plusieurs backends dans Trident pour Kubernetes ?

Trident peut prendre en charge simultanément de nombreux backends, soit avec le même pilote, soit avec des pilotes différents.



=== Comment Trident stocke-t-il les identifiants du backend ?

Trident stocke les identifiants du backend sous forme de Secrets Kubernetes.



=== Comment Trident sélectionne-t-il un backend spécifique ?

Si les attributs du backend ne peuvent pas être utilisés pour sélectionner automatiquement les pools appropriés pour une classe, les  `storagePools` et  `additionalStoragePools` paramètres sont utilisés pour sélectionner un ensemble spécifique de pools.



=== Comment puis-je m'assurer que Trident ne sera pas provisionné à partir d'un backend spécifique ?

Le  `excludeStoragePools` paramètre est utilisé pour filtrer l'ensemble des pools que Trident utilise pour le provisionnement et supprimera tous les pools correspondants.



=== S'il existe plusieurs backends du même type, comment Trident sélectionne-t-il celui à utiliser ?

S'il existe plusieurs backends configurés du même type, Trident sélectionne le backend approprié en fonction des paramètres présents dans  `StorageClass` et  `PersistentVolumeClaim`. Par exemple, s'il existe plusieurs backends de pilote ontap-nas, Trident tente de faire correspondre les paramètres dans le  `StorageClass` et  `PersistentVolumeClaim` combinés et de trouver un backend capable de répondre aux exigences listées dans  `StorageClass` et  `PersistentVolumeClaim`. Si plusieurs backends correspondent à la requête, Trident en sélectionne un au hasard.



=== Trident prend-il en charge le protocole CHAP bidirectionnel avec Element/SolidFire ?

Oui.



=== Comment Trident déploie-t-il des Qtrees sur un volume ONTAP ? Combien de Qtrees peuvent être déployés sur un seul volume ?

Le  `ontap-nas-economy` pilote crée jusqu'à 200 Qtrees dans le même volume FlexVol (configurable entre 50 et 300), 100 000 Qtrees par nœud de cluster et 2,4 M par cluster. Lorsque vous saisissez un nouveau  `PersistentVolumeClaim` qui est pris en charge par le pilote économique, le pilote vérifie si un volume FlexVol existe déjà et peut prendre en charge le nouveau Qtree. Si le volume FlexVol n'existe pas pour prendre en charge le Qtree, un nouveau volume FlexVol est créé.



=== Comment puis-je configurer les permissions Unix pour les volumes provisionnés sur ONTAP NAS ?

Vous pouvez définir les permissions Unix sur le volume provisionné par Trident en définissant un paramètre dans le fichier de définition du backend.



=== Comment puis-je configurer un ensemble explicite d'options de montage NFS ONTAP lors du provisionnement d'un volume ?

Par défaut, Trident ne configure aucune option de montage avec Kubernetes. Pour spécifier les options de montage dans la classe de stockage Kubernetes, suivez l'exemple fourni link:https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-samples/storage-class-ontapnas-k8s1.8-mountoptions.yaml["ici"^].



=== Comment puis-je configurer les volumes provisionnés selon une règle d'export ?

Pour autoriser les hôtes concernés à accéder à un volume, utilisez le  `exportPolicy` paramètre configuré dans le fichier de définition du backend.



=== Comment configurer le chiffrement du volume via Trident avec ONTAP ?

Vous pouvez configurer le chiffrement sur le volume provisionné par Trident en utilisant le paramètre encryption dans le fichier de définition du backend. Pour plus d'informations, consultez : link:trident-reco/security-reco.html#use-trident-with-nve-and-nae["Comment Trident fonctionne avec NVE et NAE"]



=== Quelle est la meilleure façon de mettre en œuvre la QoS pour ONTAP via Trident ?

Utilisez  `StorageClasses` pour implémenter la QoS pour ONTAP.



=== Comment spécifier un provisionnement fin ou épais via Trident ?

Les pilotes ONTAP prennent en charge le provisionnement fin ou épais. Les pilotes ONTAP utilisent par défaut le provisionnement fin. Si un provisionnement épais est souhaité, vous devez configurer soit le fichier de définition du backend, soit le  `StorageClass`. Si les deux sont configurés,  `StorageClass` prend le dessus. Configurez ce qui suit pour ONTAP :

. Sur `StorageClass`, définissez l'attribut  `provisioningType` sur épais.
. Dans le fichier de définition du backend, activez les volumes épais en définissant  `backend spaceReserve parameter` comme volume.




=== Comment puis-je m'assurer que les volumes utilisés ne sont pas supprimés même si je supprime accidentellement le PVC ?

La protection PVC est automatiquement activée sur Kubernetes à partir de la version 1.10.



=== Puis-je augmenter la taille des PVC NFS créés par Trident ?

Oui. Vous pouvez étendre un PVC créé par Trident. Notez que l'autogrow de volume est une fonctionnalité ONTAP qui ne s'applique pas à Trident.



=== Puis-je importer un volume alors qu'il est en mode SnapMirror Data Protection (DP) ou hors ligne ?

L'importation du volume échoue si le volume externe est en mode DP ou est hors ligne. Vous recevez le message d'erreur suivant :

[listing]
----
Error: could not import volume: volume import failed to get size of volume: volume <name> was not found (400 Bad Request) command terminated with exit code 1.
Make sure to remove the DP mode or put the volume online before importing the volume.
----


=== Comment le quota de ressources est-il traduit dans un cluster NetApp ?

Le quota de ressources de stockage Kubernetes doit fonctionner tant que le stockage NetApp dispose de capacité. Lorsque le stockage NetApp ne peut pas respecter les paramètres de quota Kubernetes en raison d'un manque de capacité, Trident essaie de provisionner mais échoue.



=== Puis-je créer des instantanés de volume avec Trident ?

Oui. La création d'instantanés de volumes à la demande et de volumes persistants à partir d'instantanés est prise en charge par Trident. Pour créer des volumes persistants (PVs) à partir d'instantanés, assurez-vous que la  `VolumeSnapshotDataSource` feature gate a été activée.



=== Quels sont les pilotes qui prennent en charge les instantanés de volume Trident ?

À ce jour, la prise en charge des instantanés à la demande est disponible pour nos `ontap-nas`, `ontap-nas-flexgroup`, `ontap-san`, `ontap-san-economy`, `solidfire-san` et `azure-netapp-files` pilotes backend.



=== Comment puis-je effectuer une sauvegarde instantanée d'un volume provisionné par Trident avec ONTAP ?

Cette fonctionnalité est disponible sur  `ontap-nas`, `ontap-san`, et  `ontap-nas-flexgroup` pilotes. Vous pouvez également spécifier un  `snapshotPolicy` pour le  `ontap-san-economy` pilote au niveau FlexVol.

Cette fonctionnalité est également disponible sur les `ontap-nas-economy` pilotes, mais avec une granularité au niveau du volume FlexVol et non au niveau de la granularité du qtree. Pour activer la possibilité de créer des instantanés des volumes provisionnés par Trident, définissez l’option du paramètre backend `snapshotPolicy` sur la stratégie d’instantané souhaitée telle que définie sur le backend ONTAP. Les instantanés créés par le contrôleur de stockage ne sont pas connus de Trident.



=== Puis-je définir un pourcentage de réserve de snapshot pour un volume provisionné via Trident ?

Oui, vous pouvez réserver un pourcentage spécifique d'espace disque pour le stockage des copies de snapshots via Trident en définissant l'attribut  `snapshotReserve` dans le fichier de définition du backend. Si vous avez configuré  `snapshotPolicy` et  `snapshotReserve` dans le fichier de définition du backend, le pourcentage de réservation des snapshots est défini selon le pourcentage  `snapshotReserve` mentionné dans le fichier backend. Si le nombre de pourcentage  `snapshotReserve` n'est pas mentionné, ONTAP prend par défaut le pourcentage de réservation des snapshots comme 5. Si l'option  `snapshotPolicy` est définie sur none, le pourcentage de réservation des snapshots est fixé à 0.



=== Puis-je accéder directement au répertoire des snapshots de volume et copier des fichiers ?

Oui, vous pouvez accéder au répertoire des instantanés sur le volume provisionné par Trident en configurant le  `snapshotDir` paramètre dans le fichier de définition du backend.



=== Puis-je configurer SnapMirror pour les volumes via Trident ?

Actuellement, SnapMirror doit être configuré en externe en utilisant l'interface de ligne de commande ONTAP ou OnCommand System Manager.



=== Comment restaurer des volumes persistants à un instantané ONTAP spécifique ?

Pour restaurer un volume à un snapshot ONTAP, procédez comme suit :

. Mettez en veille le pod d'application qui utilise le volume Persistent.
. Restaurez l'instantané requis via l'interface de ligne de commande ONTAP ou OnCommand System Manager.
. Redémarrez le pod d'application.




=== Trident peut-il provisionner des volumes sur des SVM ayant un miroir de partage de charge configuré ?

Des miroirs de répartition de charge peuvent être créés pour les volumes racine des SVM qui diffusent des données via NFS. ONTAP met automatiquement à jour les miroirs de répartition de charge pour les volumes créés par Trident. Cela peut entraîner des délais lors du montage des volumes. Lorsque plusieurs volumes sont créés avec Trident, le provisionnement d'un volume dépend de la mise à jour du miroir de répartition de charge par ONTAP.



=== Comment puis-je séparer l'utilisation des classes de stockage pour chaque client/locataire ?

Kubernetes n'autorise pas les classes de stockage dans les espaces de noms. Cependant, vous pouvez utiliser Kubernetes pour limiter l'utilisation d'une classe de stockage spécifique par espace de noms en utilisant les quotas de ressources de stockage, qui sont définis par espace de noms. Pour refuser à un espace de noms spécifique l'accès à un stockage spécifique, définissez le quota de ressources de cette classe de stockage à 0.
