---
sidebar: sidebar 
permalink: trident-managing-k8s/uninstall-trident.html 
keywords: uninstall, Trident, methods, operator, tridentctl, helm, downgrade, obliviate, crds, wipeout, downgrade 
summary: Vous devez utiliser la même méthode pour désinstaller Trident que celle que vous avez utilisée pour installer Trident. Si vous avez besoin d’un correctif pour des bugs observés après une mise à niveau, des problèmes de dépendances ou une mise à niveau infructueuse ou incomplète, vous devez désinstaller Trident et réinstaller la version précédente en suivant les instructions spécifiques à cette version. 
---
= Désinstaller Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez utiliser la même méthode pour désinstaller Trident que celle que vous avez utilisée pour l’installer.

.À propos de cette tâche
* Si vous avez besoin d’un correctif pour des bugs observés après une mise à niveau, des problèmes de dépendances ou une mise à niveau incomplète ou ayant échoué, vous devez désinstaller Trident et réinstaller la version précédente en utilisant les instructions spécifiques pour cela link:../earlier-versions.html["version"]. C’est la seule méthode recommandée pour _revenir_ à une version antérieure.
* Pour faciliter la mise à niveau et la réinstallation, la désinstallation de Trident ne supprime pas les CRD ni les objets associés créés par Trident. Si vous devez supprimer complètement Trident et toutes ses données, consultez link:../troubleshooting.html#completely-remove-trident-and-crds["Supprimez complètement Trident et les CRD"].


.Avant de commencer
Si vous mettez hors service des clusters Kubernetes, vous devez supprimer toutes les applications qui utilisent des volumes créés par Trident avant de désinstaller. Cela garantit que les PVC sont dépubliés sur les nœuds Kubernetes avant leur suppression.



== Déterminez la méthode d'installation d'origine

Vous devez utiliser la même méthode pour désinstaller Trident que celle que vous avez utilisée pour l’installer. Avant de désinstaller, vérifiez quelle version vous avez utilisée pour installer Trident à l’origine.

. Utilisez  `kubectl get pods -n trident` pour examiner les pods.
+
** S'il n'y a pas de module opérateur, Trident a été installé à l'aide de `tridentctl`.
** S'il existe un pod opérateur, Trident a été installé à l'aide de l'opérateur Trident, soit manuellement, soit à l'aide de Helm.


. S'il existe un module opérateur, utilisez  `kubectl describe tproc trident` pour déterminer si Trident a été installé à l'aide de Helm.
+
** S'il y a une étiquette Helm, Trident a été installé avec Helm.
** S'il n'y a pas d'étiquette Helm, Trident a été installé manuellement à l'aide de l'opérateur Trident.






== Désinstaller une installation de l'opérateur Trident

Vous pouvez désinstaller une installation de l'opérateur Trident manuellement ou à l'aide de Helm.



=== Désinstaller l'installation manuelle

Si vous avez installé Trident à l'aide de l'opérateur, vous pouvez le désinstaller en procédant de l'une des manières suivantes :

. **Modifier `TridentOrchestrator` CR et définir l'indicateur de désinstallation**:
+
[listing]
----
kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"uninstall":true}}'
----
+
Lorsque le  `uninstall` flag est défini sur  `true`, l’opérateur Trident désinstalle Trident, mais ne supprime pas le TridentOrchestrator lui-même. Vous devez nettoyer le TridentOrchestrator et en créer un nouveau si vous souhaitez installer à nouveau Trident.

. **Supprimer `TridentOrchestrator`** : En supprimant le `TridentOrchestrator` CR qui a été utilisé pour déployer Trident, vous demandez à l’opérateur de désinstaller Trident. L’opérateur traite la suppression de `TridentOrchestrator` et procède à la suppression du déploiement Trident et du daemonset, supprimant les pods Trident qu’il avait créés lors de l’installation.
+
[listing]
----
kubectl delete -f deploy/<bundle.yaml> -n <namespace>
----




=== Désinstaller l'installation Helm

Si vous avez installé Trident à l'aide de Helm, vous pouvez le désinstaller en utilisant  `helm uninstall`.

[listing]
----
#List the Helm release corresponding to the Trident install.
helm ls -n trident
NAME          NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
trident       trident         1               2021-04-20 00:26:42.417764794 +0000 UTC deployed        trident-operator-21.07.1        21.07.1

#Uninstall Helm release to remove Trident
helm uninstall trident -n trident
release "trident" uninstalled
----


== Désinstaller une `tridentctl` installation

Utilisez la commande  `uninstall` dans  `tridentctl` pour supprimer toutes les ressources associées à Trident à l’exception des CRDs et des objets associés :

[listing]
----
./tridentctl uninstall -n <namespace>
----