---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-tridentctl.html 
keywords: upgrade, trident, methods, operator, tridentctl, helm 
summary: 'Vous pouvez facilement mettre à niveau une installation Trident existante en utilisant `tridentctl`.' 
---
= Mise à niveau avec tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez facilement mettre à niveau une installation Trident existante en utilisant `tridentctl`.

.À propos de cette tâche
La désinstallation et la réinstallation de Trident constituent une mise à niveau. Lorsque vous désinstallez Trident, la Persistent Volume Claim (PVC) et le Persistent Volume (PV) utilisés par le déploiement Trident ne sont pas supprimés. Les PV déjà provisionnés restent disponibles pendant que Trident est hors ligne, et Trident provisionnera des volumes pour toutes les PVC créées entre-temps après son retour en ligne.

.Avant de commencer
Vérifiez link:upgrade-trident.html#step-3-select-an-upgrade-method["Sélectionnez une méthode de mise à niveau"] avant la mise à niveau en utilisant  `tridentctl`.

.Étapes
. Exécutez la commande de désinstallation dans `tridentctl` pour supprimer toutes les ressources associées à Trident à l’exception des CRD et des objets associés.
+
[listing]
----
./tridentctl uninstall -n <namespace>
----
. Réinstallez Trident. Reportez-vous à link:../trident-install/kubernetes-deploy-tridentctl.html#install-trident-using-tridentctl["Installez Trident à l'aide de tridentctl"].



IMPORTANT: N’interrompez pas le processus de mise à niveau. Assurez-vous que l’installateur s’exécute jusqu’à la fin.
