---
sidebar: sidebar 
permalink: trident-use/gcnv-examples.html 
keywords: trident backend, google cloud netapp volumes, nfs volumes, nfs 
summary: Découvrez NFS et les options de configuration du backend NFS pour Google Cloud NetApp Volumes et consultez des exemples de configuration. 
---
= Options et exemples de configuration du backend Google Cloud NetApp Volumes
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez les options de configuration backend pour Google Cloud NetApp Volumes et consultez des exemples de configuration.



== Options de configuration du backend

Chaque backend provisionne des volumes dans une seule région Google Cloud. Pour créer des volumes dans d'autres régions, vous pouvez définir des backends supplémentaires.

[cols="1, 2, 1"]
|===
| Paramètre | Description | Défaut 


| `version` |  | Toujours 1 


| `storageDriverName` | Nom du pilote de stockage | La valeur de `storageDriverName` doit être spécifiée comme « google-cloud-netapp-volumes ». 


| `backendName` | (Facultatif) Nom personnalisé du stockage backend | Nom du driver + "_" + partie de la clé API 


| `storagePools` | Paramètre optionnel utilisé pour spécifier les pools de stockage pour la création de volumes. |  


| `projectNumber` | Numéro de projet du compte Google Cloud. La valeur se trouve sur la page d'accueil du portail Google Cloud. |  


| `location` | L'emplacement Google Cloud où Trident crée les volumes GCNV. Lors de la création de clusters Kubernetes interrégionaux, les volumes créés dans un  `location` peuvent être utilisés dans des charges de travail planifiées sur des nœuds répartis dans plusieurs régions Google Cloud. Le trafic interrégional engendre des coûts supplémentaires. |  


| `apiKey` | Clé API pour le compte de service Google Cloud avec le  `netapp.admin` rôle. Elle inclut le contenu au format JSON du fichier de clé privée d’un compte de service Google Cloud (copié tel quel dans le fichier de configuration du backend). Le  `apiKey` doit inclure des paires clé-valeur pour les clés suivantes :  `type`,  `project_id`,  `client_email`,  `client_id`,  `auth_uri`,  `token_uri`,  `auth_provider_x509_cert_url` et  `client_x509_cert_url`. |  


| `nfsMountOptions` | Contrôle précis des options de montage NFS. | "nfsvers=3" 


| `limitVolumeSize` | L'approvisionnement échoue si la taille du volume demandée est supérieure à cette valeur. | "" (non appliqué par défaut) 


| `serviceLevel` | Le niveau de service d'un pool de stockage et de ses volumes. Les valeurs sont `flex`, `standard`, `premium` ou  `extreme`. |  


| `labels` | Ensemble d'étiquettes arbitraires au format JSON à appliquer aux volumes | "" 


| `network` | Réseau Google Cloud utilisé pour les volumes GCNV. |  


| `debugTraceFlags` | Options de débogage à utiliser lors du dépannage. Exemple, `{"api":false, "method":true}`. N'utilisez cette option que si vous effectuez un dépannage et avez besoin d'un journal détaillé. | null 


| `nasType` | Configurez la création de volumes NFS ou SMB. Les options sont  `nfs`,  `smb` ou null. La valeur null correspond par défaut à la création de volumes NFS. | `nfs` 


| `supportedTopologies` | Représente une liste de régions et de zones prises en charge par ce backend. Pour plus d'informations, consultez link:../trident-use/csi-topology.html["Utiliser la topologie CSI"]. Par exemple :
`supportedTopologies:
- topology.kubernetes.io/region: asia-east1
  topology.kubernetes.io/zone: asia-east1-a` |  
|===


== Options de provisionnement de volume

Vous pouvez contrôler le provisionnement des volumes par défaut dans la section  `defaults` du fichier de configuration.

[cols=",,"]
|===
| Paramètre | Description | Défaut 


| `exportRule` | Les règles d'exportation pour les nouveaux volumes. Doit être une liste séparée par des virgules de toute combinaison d'adresses IPv4. | "0.0.0.0/0" 


| `snapshotDir` | Accès au  `.snapshot` répertoire | "true" pour NFSv4 "false" pour NFSv3 


| `snapshotReserve` | Pourcentage du volume réservé aux instantanés | "" (accepter la valeur par défaut de 0) 


| `unixPermissions` | Les permissions Unix des nouveaux volumes (4 chiffres octaux). | "" 
|===


== Exemples de configurations

Les exemples suivants présentent des configurations de base qui laissent la plupart des paramètres par défaut. C'est la manière la plus simple de définir un backend.

.Configuration minimale
[%collapsible]
====
Il s'agit de la configuration minimale absolue du backend. Avec cette configuration, Trident découvre tous vos pools de stockage délégués à Google Cloud NetApp Volumes à l'emplacement configuré, et place les nouveaux volumes sur l'un de ces pools de façon aléatoire. Parce que `nasType` est omis, la `nfs` configuration par défaut s'applique et le backend provisionnera des volumes NFS.

Cette configuration est idéale lorsque vous débutez avec Google Cloud NetApp Volumes et que vous faites des essais, mais en pratique vous devrez probablement définir une portée supplémentaire pour les volumes que vous provisionnez.

[source, yaml]
----
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-gcnv-secret
type: Opaque
stringData:
  private_key_id: f2cb6ed6d7cc10c453f7d3406fc700c5df0ab9ec
  private_key: |
    -----BEGIN PRIVATE KEY-----
    znHczZsrrtHisIsAbOguSaPIKeyAZNchRAGzlzZE4jK3bl/qp8B4Kws8zX5ojY9m
    znHczZsrrtHisIsAbOguSaPIKeyAZNchRAGzlzZE4jK3bl/qp8B4Kws8zX5ojY9m
    znHczZsrrtHisIsAbOguSaPIKeyAZNchRAGzlzZE4jK3bl/qp8B4Kws8zX5ojY9m
    XsYg6gyxy4zq7OlwWgLwGa==
    -----END PRIVATE KEY-----

---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-gcnv
spec:
  version: 1
  storageDriverName: google-cloud-netapp-volumes
  projectNumber: "123455380079"
  location: europe-west6
  serviceLevel: premium
  apiKey:
    type: service_account
    project_id: my-gcnv-project
    client_email: myproject-prod@my-gcnv-project.iam.gserviceaccount.com
    client_id: "103346282737811234567"
    auth_uri: https://accounts.google.com/o/oauth2/auth
    token_uri: https://oauth2.googleapis.com/token
    auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
    client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/myproject-prod%40my-gcnv-project.iam.gserviceaccount.com
  credentials:
    name: backend-tbc-gcnv-secret
----
====
.Configuration pour les volumes SMB
[%collapsible]
====
[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-gcnv1
  namespace: trident
spec:
  version: 1
  storageDriverName: google-cloud-netapp-volumes
  projectNumber: "123456789"
  location: asia-east1
  serviceLevel: flex
  nasType: smb
  apiKey:
    type: service_account
    project_id: cloud-native-data
    client_email: trident-sample@cloud-native-data.iam.gserviceaccount.com
    client_id: "123456789737813416734"
    auth_uri: https://accounts.google.com/o/oauth2/auth
    token_uri: https://oauth2.googleapis.com/token
    auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
    client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/trident-sample%40cloud-native-data.iam.gserviceaccount.com
  credentials:
    name: backend-tbc-gcnv-secret
----
====
.Configuration avec le filtre StoragePools
[%collapsible]
====
[source, yaml]
----
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-gcnv-secret
type: Opaque
stringData:
  private_key_id: f2cb6ed6d7cc10c453f7d3406fc700c5df0ab9ec
  private_key: |
    -----BEGIN PRIVATE KEY-----
    znHczZsrrtHisIsAbOguSaPIKeyAZNchRAGzlzZE4jK3bl/qp8B4Kws8zX5ojY9m
    znHczZsrrtHisIsAbOguSaPIKeyAZNchRAGzlzZE4jK3bl/qp8B4Kws8zX5ojY9m
    znHczZsrrtHisIsAbOguSaPIKeyAZNchRAGzlzZE4jK3bl/qp8B4Kws8zX5ojY9m
    XsYg6gyxy4zq7OlwWgLwGa==
    -----END PRIVATE KEY-----

---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-gcnv
spec:
  version: 1
  storageDriverName: google-cloud-netapp-volumes
  projectNumber: "123455380079"
  location: europe-west6
  serviceLevel: premium
  storagePools:
    - premium-pool1-europe-west6
    - premium-pool2-europe-west6
  apiKey:
    type: service_account
    project_id: my-gcnv-project
    client_email: myproject-prod@my-gcnv-project.iam.gserviceaccount.com
    client_id: "103346282737811234567"
    auth_uri: https://accounts.google.com/o/oauth2/auth
    token_uri: https://oauth2.googleapis.com/token
    auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
    client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/myproject-prod%40my-gcnv-project.iam.gserviceaccount.com
  credentials:
    name: backend-tbc-gcnv-secret
----
====
.Configuration du pool virtuel
[%collapsible]
====
Cette configuration backend définit plusieurs pools virtuels dans un seul fichier. Les pools virtuels sont définis dans la  `storage` section. Ils sont utiles lorsque vous disposez de plusieurs pools de stockage prenant en charge différents niveaux de service et que vous souhaitez créer des classes de stockage dans Kubernetes pour les représenter. Les étiquettes des pools virtuels sont utilisées pour différencier les pools. Par exemple, dans l'exemple ci-dessous,  `performance` label et  `serviceLevel` type sont utilisés pour différencier les pools virtuels.

Vous pouvez également définir des valeurs par défaut applicables à tous les pools virtuels et remplacer les valeurs par défaut pour des pools virtuels individuels. Dans l'exemple suivant,  `snapshotReserve` et  `exportRule` servent de valeurs par défaut pour tous les pools virtuels.

Pour plus d'informations, consultez link:../trident-concepts/virtual-storage-pool.html["Pools virtuels"].

[source, yaml]
----
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-gcnv-secret
type: Opaque
stringData:
  private_key_id: f2cb6ed6d7cc10c453f7d3406fc700c5df0ab9ec
  private_key: |
    -----BEGIN PRIVATE KEY-----
    znHczZsrrtHisIsAbOguSaPIKeyAZNchRAGzlzZE4jK3bl/qp8B4Kws8zX5ojY9m
    znHczZsrrtHisIsAbOguSaPIKeyAZNchRAGzlzZE4jK3bl/qp8B4Kws8zX5ojY9m
    znHczZsrrtHisIsAbOguSaPIKeyAZNchRAGzlzZE4jK3bl/qp8B4Kws8zX5ojY9m
    znHczZsrrtHisIsAbOguSaPIKeyAZNchRAGzlzZE4jK3bl/qp8B4Kws8zX5ojY9m
    XsYg6gyxy4zq7OlwWgLwGa==
    -----END PRIVATE KEY-----

---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-gcnv
spec:
  version: 1
  storageDriverName: google-cloud-netapp-volumes
  projectNumber: "123455380079"
  location: europe-west6
  apiKey:
    type: service_account
    project_id: my-gcnv-project
    client_email: myproject-prod@my-gcnv-project.iam.gserviceaccount.com
    client_id: "103346282737811234567"
    auth_uri: https://accounts.google.com/o/oauth2/auth
    token_uri: https://oauth2.googleapis.com/token
    auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
    client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/myproject-prod%40my-gcnv-project.iam.gserviceaccount.com
  credentials:
    name: backend-tbc-gcnv-secret
  defaults:
    snapshotReserve: "10"
    exportRule: 10.0.0.0/24
  storage:
    - labels:
        performance: extreme
      serviceLevel: extreme
      defaults:
        snapshotReserve: "5"
        exportRule: 0.0.0.0/0
    - labels:
        performance: premium
      serviceLevel: premium
    - labels:
        performance: standard
      serviceLevel: standard
----
====
.Identité cloud pour GKE
[%collapsible]
====
[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-gcp-gcnv
spec:
  version: 1
  storageDriverName: google-cloud-netapp-volumes
  projectNumber: '012345678901'
  network: gcnv-network
  location: us-west2
  serviceLevel: Premium
  storagePool: pool-premium1
----
====
.Configuration des topologies prises en charge
[%collapsible]
====
Trident facilite le provisionnement des volumes pour les charges de travail en fonction des régions et des zones de disponibilité. Le  `supportedTopologies` bloc dans cette configuration backend est utilisé pour fournir une liste de régions et de zones par backend. Les valeurs de région et de zone spécifiées ici doivent correspondre aux valeurs de région et de zone des étiquettes sur chaque nœud de cluster Kubernetes. Ces régions et zones représentent la liste des valeurs autorisées pouvant être fournies dans une classe de stockage. Pour les classes de stockage qui contiennent un sous-ensemble des régions et zones fournies dans un backend, Trident crée les volumes dans la région et la zone mentionnées. Pour plus d'informations, consultez link:../trident-use/csi-topology.html["Utiliser la topologie CSI"].

[source, yaml]
----
---
version: 1
storageDriverName: google-cloud-netapp-volumes
subscriptionID: 9f87c765-4774-fake-ae98-a721add45451
tenantID: 68e4f836-edc1-fake-bff9-b2d865ee56cf
clientID: dd043f63-bf8e-fake-8076-8de91e5713aa
clientSecret: SECRET
location: asia-east1
serviceLevel: flex
supportedTopologies:
  - topology.kubernetes.io/region: asia-east1
    topology.kubernetes.io/zone: asia-east1-a
  - topology.kubernetes.io/region: asia-east1
    topology.kubernetes.io/zone: asia-east1-b

----
====


== Et ensuite ?

Après avoir créé le fichier de configuration, exécutez la commande suivante :

[listing]
----
kubectl create -f <backend-file>
----
Pour vérifier que le backend a bien été créé, exécutez la commande suivante :

[listing]
----
kubectl get tridentbackendconfig

NAME               BACKEND NAME       BACKEND UUID                           PHASE   STATUS
backend-tbc-gcnv   backend-tbc-gcnv   b2fd1ff9-b234-477e-88fd-713913294f65   Bound   Success
----
Si la création du backend échoue, cela signifie qu'il y a un problème avec la configuration du backend. Vous pouvez décrire le backend à l'aide de la commande  `kubectl get tridentbackendconfig <backend-name>` ou consulter les journaux pour déterminer la cause en exécutant la commande suivante :

[listing]
----
tridentctl logs
----
Après avoir identifié et corrigé le problème lié au fichier de configuration, vous pouvez supprimer le backend et exécuter à nouveau la commande de création.



== Définitions des classes de stockage

L'exemple suivant est une  `StorageClass`définition de base qui fait référence au backend ci-dessus.

[source, yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcnv-nfs-sc
provisioner: csi.trident.netapp.io
parameters:
  backendType: "google-cloud-netapp-volumes"
----
*Exemples de définitions utilisant le champ  `parameter.selector` :*

En utilisant  `parameter.selector`, vous pouvez spécifier pour chaque  `StorageClass` le link:../trident-concepts/virtual-storage-pool.html["pool virtuel"] utilisé pour héberger un volume. Le volume aura les aspects définis dans le pool choisi.

[source, yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: extreme-sc
provisioner: csi.trident.netapp.io
parameters:
  selector: performance=extreme
  backendType: google-cloud-netapp-volumes

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: premium-sc
provisioner: csi.trident.netapp.io
parameters:
  selector: performance=premium
  backendType: google-cloud-netapp-volumes

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-sc
provisioner: csi.trident.netapp.io
parameters:
  selector: performance=standard
  backendType: google-cloud-netapp-volumes
----
Pour plus de détails sur les classes de stockage, reportez-vous à link:../trident-use/create-stor-class.html["Créer une classe de stockage"^].



=== Exemples de définitions pour les volumes SMB

En utilisant  `nasType`,  `node-stage-secret-name` et  `node-stage-secret-namespace`, vous pouvez spécifier un volume SMB et fournir les informations d'identification Active Directory requises. Tout utilisateur/mot de passe Active Directory, avec ou sans autorisations, peut être utilisé pour le secret de l'étape du nœud.

.Configuration de base sur l'espace de noms par défaut
[%collapsible]
====
[source, yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcnv-sc-smb
provisioner: csi.trident.netapp.io
parameters:
  backendType: "google-cloud-netapp-volumes"
  trident.netapp.io/nasType: "smb"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "default"
----
====
.Utilisation de secrets différents par espace de noms
[%collapsible]
====
[source, yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcnv-sc-smb
provisioner: csi.trident.netapp.io
parameters:
  backendType: "google-cloud-netapp-volumes"
  trident.netapp.io/nasType: "smb"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: ${pvc.namespace}
----
====
.Utilisation de secrets différents par volume
[%collapsible]
====
[source, yaml]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gcnv-sc-smb
provisioner: csi.trident.netapp.io
parameters:
  backendType: "google-cloud-netapp-volumes"
  trident.netapp.io/nasType: "smb"
  csi.storage.k8s.io/node-stage-secret-name: ${pvc.name}
  csi.storage.k8s.io/node-stage-secret-namespace: ${pvc.namespace}
----
====

NOTE: `nasType: smb`Filtres pour les pools prenant en charge les volumes SMB. `nasType: nfs` ou  `nasType: null`filtres pour les pools NFS.



=== Exemple de définition du PVC

[source, yaml]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gcnv-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: gcnv-nfs-sc
----
Pour vérifier si le PVC est lié, exécutez la commande suivante :

[listing]
----
kubectl get pvc gcnv-nfs-pvc

NAME          STATUS   VOLUME                                    CAPACITY  ACCESS MODES   STORAGECLASS AGE
gcnv-nfs-pvc  Bound    pvc-b00f2414-e229-40e6-9b16-ee03eb79a213  100Gi     RWX            gcnv-nfs-sc  1m
----