---
sidebar: sidebar 
permalink: trident-use/ontap-san.html 
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Découvrez comment configurer un backend ONTAP avec les pilotes SAN ONTAP. 
---
= Présentation du pilote ONTAP SAN
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez comment configurer un backend ONTAP avec les pilotes SAN ONTAP et Cloud Volumes ONTAP.



== Détails du pilote ONTAP SAN

Trident fournit les pilotes de stockage SAN suivants pour communiquer avec le cluster ONTAP. Les modes d'accès pris en charge sont : _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2"]
|===
| Pilote | Protocole | volumeMode | Modes d'accès pris en charge | Systèmes de fichiers pris en charge 


| `ontap-san`  a| 
iSCSI SCSI sur FC
 a| 
Bloc
 a| 
RWO, ROX, RWX, RWOP
 a| 
Aucun système de fichiers ; périphérique bloc brut



| `ontap-san`  a| 
iSCSI SCSI sur FC
 a| 
Système de fichiers
 a| 
RWO, RWOP

ROX et RWX ne sont pas disponibles en mode volume du système de fichiers.
 a| 
`xfs`, `ext3`, `ext4`



| `ontap-san`  a| 
NVMe/TCP

Voir <<Considérations supplémentaires pour NVMe/TCP>>.
 a| 
Bloc
 a| 
RWO, ROX, RWX, RWOP
 a| 
Aucun système de fichiers ; périphérique bloc brut



| `ontap-san`  a| 
NVMe/TCP

Voir <<Considérations supplémentaires pour NVMe/TCP>>.
 a| 
Système de fichiers
 a| 
RWO, RWOP

ROX et RWX ne sont pas disponibles en mode volume du système de fichiers.
 a| 
`xfs`, `ext3`, `ext4`



| `ontap-san-economy`  a| 
iSCSI
 a| 
Bloc
 a| 
RWO, ROX, RWX, RWOP
 a| 
Aucun système de fichiers ; périphérique bloc brut



| `ontap-san-economy`  a| 
iSCSI
 a| 
Système de fichiers
 a| 
RWO, RWOP

ROX et RWX ne sont pas disponibles en mode volume du système de fichiers.
 a| 
`xfs`, `ext3`, `ext4`

|===
[WARNING]
====
* Utilisez  `ontap-san-economy` uniquement si le nombre d’utilisations du volume persistant doit être supérieur à link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["limites de volume ONTAP prises en charge"^].
* Utilisez  `ontap-nas-economy` uniquement si le nombre d'utilisations de volumes persistants est censé être supérieur à link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["limites de volume ONTAP prises en charge"^] et que le pilote  `ontap-san-economy` ne peut pas être utilisé.
* N'utilisez pas  `ontap-nas-economy` si vous prévoyez un besoin de protection des données, de reprise après sinistre ou de mobilité.
* NetApp ne recommande pas d'utiliser la croissance automatique FlexVol® dans tous les pilotes ONTAP, sauf ontap-san. En guise de solution de contournement, Trident prend en charge l'utilisation de la réserve de snapshots et adapte les volumes FlexVol® en conséquence.


====


== Autorisations de l'utilisateur

Trident doit être exécuté en tant qu'administrateur ONTAP ou SVM, généralement en utilisant l' `admin`utilisateur cluster ou un `vsadmin`utilisateur SVM, ou un utilisateur avec un nom différent ayant le même rôle. Pour les déploiements Amazon FSx for NetApp ONTAP, Trident doit être exécuté en tant qu'administrateur ONTAP ou SVM, en utilisant l'utilisateur cluster `fsxadmin` ou un `vsadmin`utilisateur SVM, ou un utilisateur avec un nom différent ayant le même rôle. L' `fsxadmin`utilisateur est un remplacement limité pour l'utilisateur administrateur du cluster.


NOTE: Si vous utilisez le  `limitAggregateUsage` paramètre, des autorisations d'administrateur de cluster sont requises. Lors de l'utilisation d'Amazon FSx for NetApp ONTAP avec Trident, le  `limitAggregateUsage` paramètre ne fonctionnera pas avec les comptes d'utilisateur  `vsadmin` et  `fsxadmin`. L'opération de configuration échouera si vous spécifiez ce paramètre.

Bien qu'il soit possible de créer un rôle plus restrictif au sein d'ONTAP qu'un pilote Trident peut utiliser, nous ne le recommandons pas. La plupart des nouvelles versions de Trident feront appel à des API supplémentaires dont il faudrait tenir compte, ce qui rend les mises à niveau difficiles et sujettes aux erreurs.



== Considérations supplémentaires pour NVMe/TCP

Trident prend en charge le protocole non-volatile memory express (NVMe) à l'aide du  `ontap-san` driver, notamment :

* IPv6
* Instantanés et clones de volumes NVMe
* Redimensionnement d'un volume NVMe
* Importation d'un volume NVMe créé en dehors de Trident afin que son cycle de vie puisse être géré par Trident
* Multipathing natif NVMe
* Arrêt progressif ou brutal des nœuds K8s (24.06)


Trident ne prend pas en charge :

* DH-HMAC-CHAP pris en charge nativement par NVMe
* Multipathing du device mapper (DM)
* chiffrement LUKS



NOTE: NVMe est pris en charge uniquement avec les API REST ONTAP et non avec ONTAPI (ZAPI).
