---
sidebar: sidebar 
permalink: trident-use/ontap-nas.html 
keywords: trident backend, ontap nas, ontap-nas, ontap-nas-economy, ontap-nas-flexgroups, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Découvrez comment configurer un backend ONTAP avec les pilotes ONTAP NAS. 
---
= Présentation du pilote ONTAP NAS
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez la configuration d'un backend ONTAP avec les pilotes NAS ONTAP et Cloud Volumes ONTAP.



== Détails du pilote ONTAP NAS

Trident fournit les pilotes de stockage NAS suivants pour communiquer avec le cluster ONTAP. Les modes d'accès pris en charge sont : _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2"]
|===
| Pilote | Protocole | volumeMode | Modes d'accès pris en charge | Systèmes de fichiers pris en charge 


| `ontap-nas`  a| 
NFS SMB
 a| 
Système de fichiers
 a| 
RWO, ROX, RWX, RWOP
 a| 
"", `nfs`, `smb`



| `ontap-nas-economy`  a| 
NFS SMB
 a| 
Système de fichiers
 a| 
RWO, ROX, RWX, RWOP
 a| 
"", `nfs`, `smb`



| `ontap-nas-flexgroup`  a| 
NFS SMB
 a| 
Système de fichiers
 a| 
RWO, ROX, RWX, RWOP
 a| 
"", `nfs`, `smb`

|===
[WARNING]
====
* Utilisez  `ontap-san-economy` uniquement si le nombre d’utilisations du volume persistant doit être supérieur à link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["limites de volume ONTAP prises en charge"^].
* Utilisez  `ontap-nas-economy` uniquement si le nombre d'utilisations de volumes persistants est censé être supérieur à link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["limites de volume ONTAP prises en charge"^] et que le pilote  `ontap-san-economy` ne peut pas être utilisé.
* N'utilisez pas  `ontap-nas-economy` si vous prévoyez un besoin de protection des données, de reprise après sinistre ou de mobilité.
* NetApp ne recommande pas d'utiliser la croissance automatique FlexVol® dans tous les pilotes ONTAP, sauf ontap-san. En guise de solution de contournement, Trident prend en charge l'utilisation de la réserve de snapshots et adapte les volumes FlexVol® en conséquence.


====


== Autorisations de l'utilisateur

Trident s'attend à être exécuté en tant qu'administrateur ONTAP ou SVM, généralement en utilisant le  `admin` cluster user ou un  `vsadmin` SVM user, ou un utilisateur avec un nom différent ayant le même rôle.

Pour les déploiements Amazon FSx for NetApp ONTAP, Trident doit être exécuté en tant qu'administrateur ONTAP ou SVM, en utilisant l'utilisateur cluster `fsxadmin` ou un utilisateur SVM `vsadmin`, ou un utilisateur avec un nom différent ayant le même rôle. L'utilisateur `fsxadmin` est un remplacement limité de l'utilisateur administrateur du cluster.


NOTE: Si vous utilisez le  `limitAggregateUsage` paramètre, des autorisations d'administrateur de cluster sont requises. Lors de l'utilisation d'Amazon FSx for NetApp ONTAP avec Trident, le  `limitAggregateUsage` paramètre ne fonctionnera pas avec les comptes d'utilisateur  `vsadmin` et  `fsxadmin`. L'opération de configuration échouera si vous spécifiez ce paramètre.

Bien qu'il soit possible de créer un rôle plus restrictif au sein d'ONTAP qu'un pilote Trident peut utiliser, nous ne le recommandons pas. La plupart des nouvelles versions de Trident feront appel à des API supplémentaires dont il faudrait tenir compte, ce qui rend les mises à niveau difficiles et sujettes aux erreurs.
