= Annotation de délai d'expiration du data mover
:allow-uri-read: 




== Annotation de délai d'expiration du data mover

Lors des opérations de sauvegarde et de restauration, vous pouvez utiliser l'annotation  `protect.trident.netapp.io/data-mover-timeout-sec` pour configurer le délai d'expiration des opérations de déplacement des données. Cette annotation spécifie la durée maximale, en secondes, pendant laquelle un data mover doit attendre qu'une opération spécifique se termine avant d'expirer. Elle est particulièrement utile dans les situations où des problèmes réseau ou d'autres facteurs peuvent entraîner le blocage des opérations de déplacement des données. Elle aide à détecter et à gérer les opérations bloquées, plutôt que de définir un délai d'expiration général pour l'ensemble du processus. Par exemple, si aucun progrès n'est réalisé lors de la restauration des données d'un volume en raison de problèmes réseau, l'opération expirera en fonction de la durée spécifiée.

Vous pouvez utiliser cette annotation dans votre fichier YAML comme indiqué ci-dessous :

[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: BackupRestore
metadata:
  name: bkp-restore-kopia
  namespace: trident-protect
  annotations: # Optional annotations to configure data movement timeout
    protect.trident.netapp.io/data-mover-timeout-sec: "2"
spec:
  appVaultRef: appvault-name
  appArchivePath: my-backup-path
  namespaceMapping: [{"source": "my-source-namespace", "destination": "my-destination-namespace"}]
  storageClassMapping:
    destination: "${destinationStorageClass}"
    source: "${sourceStorageClass}"
----
Dans cet exemple, l'annotation fait échouer l' `BackupRestore`opération si aucune progression n'a lieu dans les 2 secondes lors de l'opération de restauration.


NOTE: Si la valeur de l'annotation est inférieure ou égale à 0, l'opération échouera immédiatement.
