---
sidebar: sidebar 
permalink: trident-get-started/k8s-netapp.html 
keywords: kubernetes, netapp storage, ontap, cloud volumes ontap, santricity, element software, netapp hci, anf, azure netapp files, aws, amazon fsx 
summary: 'Le portefeuille de produits de stockage NetApp s"intègre à de nombreux aspects d"un cluster Kubernetes, offrant des capacités avancées de gestion des données qui améliorent la fonctionnalité, la capacité, les performances et la disponibilité du déploiement Kubernetes.' 
---
= Intégration de Kubernetes avec les produits NetApp
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le portefeuille de produits de stockage NetApp s'intègre à de nombreux aspects d'un cluster Kubernetes, offrant des capacités avancées de gestion des données qui améliorent la fonctionnalité, la capacité, les performances et la disponibilité du déploiement Kubernetes.



== Trident

https://docs.netapp.com/us-en/trident/["Trident"^] facilite la gestion, la protection et la migration des charges de travail conteneurisées riches en données exécutées sur Kubernetes, au sein et entre les clouds publics et les environnements sur site pour les entreprises. Trident provisionne et fournit un stockage persistant pour les conteneurs à l'aide de Trident à partir du portefeuille de solutions de stockage éprouvé et étendu NetApp dans le cloud public et sur site. Il offre également un ensemble complet de fonctionnalités avancées de gestion des données applicatives, telles que la création de snapshots, la sauvegarde et la restauration, les journaux d'activité et le clonage actif pour la protection des données, la restauration des données, l'audit des données et les cas d'utilisation de migration pour les charges de travail Kubernetes.



== ONTAP

ONTAP est le système d'exploitation de stockage multiprotocole et unifié NetApp qui offre des fonctionnalités avancées de gestion des données pour toute application. Les systèmes ONTAP disposent de configurations tout flash, hybrides ou tout HDD et proposent de nombreux modèles de déploiement différents, notamment du matériel conçu (FAS et AFF), du white-box (ONTAP Select) et du cloud uniquement (Cloud Volumes ONTAP).


NOTE: Trident prend en charge tous les modèles de déploiement ONTAP mentionnés ci-dessus.



== Cloud Volumes ONTAP

http://cloud.netapp.com/ontap-cloud?utm_source=GitHub&utm_campaign=Trident["Cloud Volumes ONTAP"^] est une appliance de stockage uniquement logicielle qui exécute le logiciel de gestion des données ONTAP dans le cloud. Vous pouvez utiliser Cloud Volumes ONTAP pour les charges de travail de production, la reprise après sinistre, DevOps, le service de partage de fichiers et la gestion de la base de données. Il étend la solution de stockage haute performance au cloud en offrant des gains d'efficacité de stockage, une haute disponibilité, la réplication des données, la hiérarchisation des données et la cohérence des applications.



== Amazon FSx for NetApp ONTAP

https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSx for NetApp ONTAP"^] est un service AWS entièrement géré qui vous permet de lancer et d’exécuter des systèmes de fichiers alimentés par le système d’exploitation de stockage NetApp ONTAP. FSx for ONTAP vous permet de bénéficier des fonctionnalités, des performances et des capacités d’administration NetApp que vous connaissez déjà, tout en profitant de la simplicité, de l’agilité, de la sécurité et de l’évolutivité du stockage de données sur AWS. FSx for ONTAP prend en charge de nombreuses fonctionnalités du système de fichiers ONTAP et des API d’administration.



== logiciel Element

https://www.netapp.com/data-management/element-software/["Élément"^] permet à l'administrateur de stockage de consolider les charges de travail en garantissant les performances et en permettant un encombrement de stockage simplifié et rationalisé. Associé à une API permettant d'automatiser tous les aspects de la gestion du stockage, Element permet aux administrateurs de stockage d'en faire plus avec moins d'efforts.



== NetApp HCI

https://www.netapp.com/virtual-desktop-infrastructure/netapp-hci/["NetApp HCI"^] simplifie la gestion et l'échelle du centre de données en automatisant les tâches de routine et en permettant aux administrateurs d'infrastructure de se concentrer sur des fonctions plus importantes.

NetApp HCI est entièrement pris en charge par Trident. Trident peut provisionner et gérer des périphériques de stockage pour des applications conteneurisées directement sur la plateforme de stockage NetApp HCI sous-jacente.



== Azure NetApp Files

https://azure.microsoft.com/en-us/services/netapp/["Azure NetApp Files"^] est un service de partage de fichiers Azure de niveau entreprise, optimisé par NetApp. Vous pouvez exécuter vos charges de travail les plus exigeantes basées sur des fichiers dans Azure nativement, avec les performances et la gestion des données avancée que vous attendez de NetApp.



== Google Cloud NetApp Volumes

https://cloud.netapp.com/cloud-volumes-service-for-gcp?utm_source=GitHub&utm_campaign=Trident["Google Cloud NetApp Volumes"^] est un service de fichiers cloud natif qui fournit des volumes NAS via NFS avec des performances 100 % flash. Ce service permet à toute charge de travail, y compris les applications existantes, de s'exécuter dans le cloud GCP. Il fournit un service entièrement géré offrant des performances élevées et constantes, un clonage instantané, une protection des données et un accès sécurisé aux instances Google Compute Engine (GCE).
