---
sidebar: sidebar 
permalink: trident-protect/trident-protect-installation.html 
keywords: install, trident, protect, requirements, registry 
summary: Si votre environnement répond aux exigences, vous pouvez suivre ces étapes pour installer Trident Protect. 
---
= Installez et configurez Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si votre environnement répond aux exigences de Trident Protect, vous pouvez suivre ces étapes pour installer Trident Protect sur votre cluster. Vous pouvez obtenir Trident Protect auprès de NetApp, ou l’installer depuis votre propre registre privé. L’installation depuis un registre privé est utile si votre cluster ne peut pas accéder à Internet.



== Installer Trident Protect

[role="tabbed-block"]
====
.Installez Trident Protect depuis NetApp
--
.Étapes
. Ajoutez le dépôt Trident Helm :
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Utilisez Helm pour installer Trident Protect. Remplacez  `<name-of-cluster>` par un nom de cluster, qui sera attribué au cluster et utilisé pour identifier les sauvegardes et instantanés du cluster :
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --version 100.2510.0 --create-namespace --namespace trident-protect
----
. Facultativement, pour activer la journalisation de débogage (recommandée pour le dépannage), utilisez :
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --set logLevel=debug --version 100.2510.0 --create-namespace --namespace trident-protect
----
+
La journalisation de débogage aide le support NetApp à résoudre les problèmes sans nécessiter de modification du niveau de journalisation ni de reproduction du problème.



--
.Installez Trident Protect à partir d'un registre privé
--
Vous pouvez installer Trident Protect à partir d'un registre d'images privé si votre cluster Kubernetes ne peut pas accéder à Internet. Dans ces exemples, remplacez les valeurs entre crochets par les informations de votre environnement :

.Étapes
. Téléchargez les images suivantes sur votre machine locale, mettez à jour les tags, puis poussez-les vers votre registre privé :
+
[source, console]
----
docker.io/netapp/controller:25.10.0
docker.io/netapp/restic:25.10.0
docker.io/netapp/kopia:25.10.0
docker.io/netapp/kopiablockrestore:25.10.0
docker.io/netapp/trident-autosupport:25.10.0
docker.io/netapp/exechook:25.10.0
docker.io/netapp/resourcebackup:25.10.0
docker.io/netapp/resourcerestore:25.10.0
docker.io/netapp/resourcedelete:25.10.0
docker.io/netapp/trident-protect-utils:v1.0.0
----
+
Par exemple :

+
[source, console]
----
docker pull docker.io/netapp/controller:25.10.0
----
+
[source, console]
----
docker tag docker.io/netapp/controller:25.10.0 <private-registry-url>/controller:25.10.0
----
+
[source, console]
----
docker push <private-registry-url>/controller:25.10.0
----
+

NOTE: Pour obtenir le graphique Helm, téléchargez d'abord le graphique Helm sur une machine ayant accès à Internet à l'aide de  `helm pull trident-protect --version 100.2510.0 --repo https://netapp.github.io/trident-protect-helm-chart`, puis copiez le fichier  `trident-protect-100.2510.0.tgz` résultant dans votre environnement hors ligne et installez-le en utilisant  `helm install trident-protect ./trident-protect-100.2510.0.tgz` au lieu de la référence du dépôt à l'étape finale.

. Créez l’espace de noms système Trident Protect :
+
[source, console]
----
kubectl create ns trident-protect
----
. Connectez-vous au registre :
+
[source, console]
----
helm registry login <private-registry-url> -u <account-id> -p <api-token>
----
. Créez un secret d'extraction à utiliser pour l'authentification du registre privé :
+
[source, console]
----
kubectl create secret docker-registry regcred --docker-username=<registry-username> --docker-password=<api-token> -n trident-protect --docker-server=<private-registry-url>
----
. Ajoutez le dépôt Trident Helm :
+
[source, console]
----
helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart
----
. Créez un fichier nommé `protectValues.yaml`. Assurez-vous qu'il contienne les paramètres Trident Protect suivants :
+
[source, yaml]
----
---
imageRegistry: <private-registry-url>
imagePullSecrets:
  - name: regcred
----
+

NOTE: Les  `imageRegistry` et  `imagePullSecrets` valeurs s'appliquent à toutes les images des composants, y compris  `resourcebackup` et  `resourcerestore`. Si vous envoyez des images vers un chemin de dépôt spécifique dans votre registre (par exemple,  `example.com:443/my-repo`), indiquez le chemin complet dans le champ du registre. Cela garantira que toutes les images sont extraites de  `<private-registry-url>/<image-name>:<tag>`.

. Utilisez Helm pour installer Trident Protect. Remplacez  `<name_of_cluster>` par le nom du cluster, qui sera attribué au cluster et utilisé pour identifier les sauvegardes et instantanés du cluster :
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name_of_cluster> --version 100.2510.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----
. Facultativement, pour activer la journalisation de débogage (recommandée pour le dépannage), utilisez :
+
[source, console]
----
helm install trident-protect netapp-trident-protect/trident-protect --set clusterName=<name-of-cluster> --set logLevel=debug --version 100.2510.0 --create-namespace --namespace trident-protect -f protectValues.yaml
----
+
La journalisation de débogage aide le support NetApp à résoudre les problèmes sans nécessiter de modification du niveau de journalisation ni de reproduction du problème.



--
====

NOTE: Pour plus d'options de configuration du chart Helm, y compris les paramètres AutoSupport et le filtrage des espaces de noms, reportez-vous à link:trident-protect-customize-installation.html#configure-additional-trident-protect-helm-chart-settings["Personnaliser l'installation de Trident Protect"].
