---
sidebar: sidebar 
permalink: trident-protect/trident-protect-upgrade.html 
keywords: trident, protect, netapp, upgrade, new, version 
summary: Vous pouvez mettre à jour Trident Protect vers la dernière version pour bénéficier de nouvelles fonctionnalités ou de correctifs de bugs. 
---
= Mettre à niveau Trident Protect
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez mettre à jour Trident Protect vers la dernière version pour bénéficier de nouvelles fonctionnalités ou de correctifs de bugs.

[NOTE]
====
* Lors de la mise à niveau depuis la version 24.10, les instantanés en cours d’exécution pendant la mise à niveau peuvent échouer. Cet échec n’empêche pas la création future d’instantanés, qu’ils soient manuels ou planifiés. Si un instantané échoue pendant la mise à niveau, vous pouvez créer un nouvel instantané manuellement pour garantir la protection de votre application.
+
Pour éviter d'éventuels dysfonctionnements, vous pouvez désactiver toutes les planifications de snapshots avant la mise à niveau et les réactiver ensuite. Cependant, cela entraîne l'absence de snapshots planifiés pendant la période de mise à niveau.

* Pour les installations de registre privé, assurez-vous que le Helm chart et les images requis pour la version cible sont disponibles dans votre registre privé, et vérifiez que vos valeurs Helm personnalisées sont compatibles avec la nouvelle version du chart. Pour plus d'informations, consultez link:trident-protect-installation.html["Installez Trident Protect à partir d'un registre privé"].


====
Pour mettre à niveau Trident Protect, procédez comme suit.

.Étapes
. Mettre à jour le dépôt Trident Helm :
+
[source, console]
----
helm repo update
----
. Mettez à niveau les CRD Trident Protect :
+

NOTE: Cette étape est nécessaire si vous effectuez une mise à niveau depuis une version antérieure à la 25.06, car les CRD sont désormais inclus dans le chart Helm Trident Protect.

+
.. Exécutez cette commande pour transférer la gestion des CRD de  `trident-protect-crds` vers  `trident-protect` :
+
[source, console]
----
kubectl get crd | grep protect.trident.netapp.io | awk '{print $1}' | xargs -I {} kubectl patch crd {} --type merge -p '{"metadata":{"annotations":{"meta.helm.sh/release-name": "trident-protect"}}}'
----
.. Exécutez cette commande pour supprimer le secret Helm pour le  `trident-protect-crds` chart :
+

NOTE: Ne désinstallez pas le  `trident-protect-crds`chart à l'aide de Helm, car cela pourrait supprimer vos CRDs et toutes les données associées.

+
[source, console]
----
kubectl delete secret -n trident-protect -l name=trident-protect-crds,owner=helm
----


. Mise à niveau de Trident Protect :
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect --version 100.2510.0 --namespace trident-protect
----
+

NOTE: Vous pouvez configurer le niveau de journalisation lors de la mise à niveau en ajoutant  `--set logLevel=debug` à la commande de mise à niveau. Le niveau de journalisation par défaut est  `warn`. La journalisation de débogage est recommandée pour le dépannage, car elle aide NetApp support à diagnostiquer les problèmes sans nécessiter de modification du niveau de journalisation ni de reproduction du problème.


