---
sidebar: sidebar 
permalink: trident-reference/rest-api.html 
keywords: rest api, get, post, json, object, backends 
summary: 'Vous pouvez utiliser directement le point de terminaison REST si vous préférez interagir avec l"API REST de Trident.' 
---
= API REST Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bien que link:trident-cl.html["commandes et options tridentctl"] soit le moyen le plus simple d'interagir avec l'API REST de Trident, vous pouvez utiliser directement le point de terminaison REST si vous préférez.



== Quand utiliser l'API REST

L'API REST est utile pour les installations avancées qui utilisent Trident comme binaire autonome dans des déploiements non-Kubernetes.

Pour une meilleure sécurité, le Trident `REST API` est limité par défaut à localhost lorsqu'il s'exécute dans un pod. Pour modifier ce comportement, vous devez définir l'argument de Trident `-address` dans la configuration de son pod.



== Utilisation de l'API REST

Pour des exemples de la façon dont ces API sont appelées, passez le drapeau de débogage (`-d`. Pour plus d'informations, consultez link:../trident-managing-k8s/tridentctl.html["Gérez Trident à l'aide de tridentctl"].

L'API fonctionne comme suit :



=== GET

`GET <trident-address>/trident/v1/<object-type>`:: Liste tous les objets de ce type.
`GET <trident-address>/trident/v1/<object-type>/<object-name>`:: Obtient les détails de l'objet nommé.




=== POST

`POST <trident-address>/trident/v1/<object-type>`:: Crée un objet du type spécifié.
+
--
* Nécessite une configuration JSON pour que l'objet soit créé. Pour la spécification de chaque type d'objet, reportez-vous à link:../trident-managing-k8s/tridentctl.html["Gérez Trident à l'aide de tridentctl"].
* Si l'objet existe déjà, le comportement varie : les backends mettent à jour l'objet existant, tandis que tous les autres types d'objet échoueront lors de l'opération.


--




=== SUPPRIMER

`DELETE <trident-address>/trident/v1/<object-type>/<object-name>`:: Supprime la ressource nommée.
+
--

NOTE: Les volumes associés aux backends ou aux classes de stockage continueront d'exister ; ils doivent être supprimés séparément. Pour plus d'informations, consultez link:../trident-managing-k8s/tridentctl.html["Gérez Trident à l'aide de tridentctl"].

--

